### ISSUE TITLE
ModMyFactory should not use an icon identical to Factorio.

### ISSUE THREAD

**Issue by mheguy** [Artentus/ModMyFactory#1]
For those who have both open or both icons on the desktop it's unnecessarily confusing. A simple palette swap would avoid any issues.

**Comment by Artentus** [comment]
I will try, but I don't have any artistic talent (I would have created a custom icon if I had).

If ModMyFactory had a different icon, which icon should links get?

**Comment by mheguy** [comment]
I whipped together a quick icon by just desaturating the existing Factorio icon. (I'm not artistically-talented either)

![mmf_icon](https://cloud.githubusercontent.com/assets/10162554/18817820/9de2ee9c-8338-11e6-85bc-5ee3f0565f88.png)

You can either download the png and convert it into an .ico yourself, or grab the .ico I created (via convertico.com) at https://dl.dropboxusercontent.com/u/33688805/MMF_Icon.ico

> which icon should links get

~~I'm not sure what links you mean.~~

Edit: Oh you mean desktop links. I think those should be the standard Factorio icon as they actually launch Factorio.

**Comment by Artentus** [comment]
Thank you, that doesn't actually look half bad.
The icon will be changed in the next release.
