### ISSUE TITLE
Crash modfactory

### ISSUE THREAD

**Issue by aleXela17** [Artentus/ModMyFactory#100]
If the length of the settings.lua file is 0 - fail
If all the lines are commented out in the settings.lua file, it fails, an example of the Rewire mod (rewire_0.0.1.zip)
Also incomprehensible failure mods reverse-factory_5.1.5, FARL_2.1.2, Orphan Finder_1.1.0, factorio-unconnected-pipe-finder_1.0.0

**Comment by Artentus** [comment]
I have decided to push back mod settings support to 1.10, so this issue is fixed for 1.9 for now.
I will probably switch to using a proper Lua interpreter instead.
