### ISSUE TITLE
MMF 1.9.0 crashes when selecting the Steam version

### ISSUE THREAD

**Issue by DurchlauchtheitFreddy** [Artentus/ModMyFactory#101]
Hey, i wanted to play the Steam-Factorio(i clicked in version manager "select Steam version"), but MMF crashes. (Factorio v. 0.16.51 ; MMF v. 1.9.0)

Error log:

[error-log.txt](https://github.com/Artentus/ModMyFactory/files/2671900/error-log.txt)

pls help :) thx

**Comment by Artentus** [comment]
I'll investigate as soon as I can manage. I'm currently not at home and will be for another couple of weeks.

**Comment by DurchlauchtheitFreddy** [comment]
anything new yet? :)

**Comment by Artentus** [comment]
I'll be back home on the 7th.

From reading the log I think it may be possible to find a quick manual workaround if you are willing to work with me. I just can't look at the code properly atm.

**Comment by DurchlauchtheitFreddy** [comment]
Ok cool, text me what to do. Maybe voice chat? It would be easier :) I have
Discord/Ts3

Am Sa., 2. Feb. 2019 um 22:17 Uhr schrieb Mathis Rech <
notifications@github.com>:

**Comment by Artentus** [comment]
Voice chat is not possible from here.

To give a little explanation on what I think happened. MMF will back up all your savegames, scenarios and mods to a folder called "Factorio-old" inside "%appdata%" the first time you add the Steam version. This is a safety measure as the Factorio folder in the same location will be tampered with.

It looks like in your case this folder already existed so when MMF tried to back up those files there was a conflict. If this is the case the temporary fix is as easy as renaming or moving that folder until MMF is done with its thing.

**Comment by DurchlauchtheitFreddy** [comment]
It's working! Thx
