### ISSUE TITLE
Experimental releases don't always show in list.

### ISSUE THREAD

**Issue by credomane** [Artentus/ModMyFactory#106]
ModMyFactory correctly showed 0.17.0 and 0.17.1 experimental versions but once 0.17.2 was released experimental versions are no longer listed. The "Show Experimental Versions" checkbox seems to do nothing in either state as well.

I thought I noticed this with 0.16 but it went stable before I could confirm it.

**Comment by Artentus** [comment]
Not a bug, the update packages got taken down server-side.

**Comment by credomane** [comment]
I can see that being the case for updating an already installed 0.17.X but why should that affect fresh installs?

If I remove all 0,17,X installs and try to install 0.17.X fresh *no* 0.17 version is listed at all. Currently resorting to manually downloading the latest 0.17.X from the website and extracting it over the old 0.17.X

**Comment by credomane** [comment]
Oh....I believe they changed the experimental download page! They added in the headless experimental downloads to the same page as the normal desktop. While also having a seperate experimental headless page.

I wish they would just add in a json file that had all the factorio versions in it with DL links. Webpage parsing is a pain. lol

**Comment by Artentus** [comment]
There is no list of versions available, I'm infering the available versions from the update packages. The website cannot be accessed programmatically because of captcha.

**Comment by credomane** [comment]
oh. I didn't realized you were doing all of that from update packages. Well damn that blows.
