### ISSUE TITLE
Take so long on searching.

### ISSUE THREAD

**Issue by SkiperTheBoss** [Artentus/ModMyFactory#107]
Hi,

i have like over one hundred mods installed and if want to use the search function it takes ages to go, it is really annoying. It feels like it search for every input the whole mods folder for existing the mods or something like that.

Is that normal or is it just me?

**Comment by Artentus** [comment]
I know about this but there is not really all that much I can do about it besides completely redesign the GUI. The slow part is the GUI layouting and not in my code.

**Comment by Artentus** [comment]
Should be a lot faster in 1.10 now.
