### ISSUE TITLE
ModMyFactory works but complains about 0.17's new hidden dependencies feature.

### ISSUE THREAD

**Issue by credomane** [Artentus/ModMyFactory#108]
The 0.17 version of the [Dectorio](https://mods.factorio.com/mod/Dectorio) mod makes use of this hidden dependency feature. You can still do everything normally but ModMyFactory wants to treat this hidden dependencies as a hard dependency by default.

Dev announcement for this feature: https://forums.factorio.com/61239

**Comment by Artentus** [comment]
Supported in 1.10
