### ISSUE TITLE
loading random mods

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory#109]
so i am using the lastest version and it was working, but now its just loading random mods even when i have 0 mods selected

**Comment by Artentus** [comment]
I need more info please.
By latest version do you mean 1.9 or 1.10pre2?
Which version of Factorio are you using?
And most importantly what mods (including all versions of them) have you installed that are showing this behaviour?

**Comment by szentigrad3** [comment]
1.10pre2, 0.17.11, i fixed it by deleting the mod-list.json and mod-settings.dat

**Comment by Artentus** [comment]
If you used 1.10pre1 or a Factorio version before 0.17.9 previously it may have messed something up.
