### ISSUE TITLE
Auto-selecting updated mods

### ISSUE THREAD

**Issue by utoxin** [Artentus/ModMyFactory#110]
The recent update added a new behavior that's getting pretty annoying.

When a mod updates from 0.16 to 0.17, it gets auto-selected as 'active', which means that you have to remember to turn off all mods, and then turn the modpack you want back on, or you'll end up with unexpected mods when you start playing. This has caught me out a couple times now.

**Comment by Artentus** [comment]
Factorios default behaviour is to enable newly installed mods. Usually I try to stay close to how Factorio handles mods to not cause confision.
It should've always worked like this so I'm confused why you think it's new behaviour.

The most logical way I see to approach this is to add an option to the settings.

**Comment by utoxin** [comment]
Hmm. Maybe the issue is just that it's been a long time since the last update cycle. And it feels wrong because the mod is disabled because it's from last version, then gets updated and turned on.

**Comment by Artentus** [comment]
I've added a setting to control this behaviour, will be in the next release.
