### ISSUE TITLE
ModMyFactory and Factorio disagree about which mods are enabled

### ISSUE THREAD

**Issue by utoxin** [Artentus/ModMyFactory#111]
Probably related to the recent change with optionally enabling mods when downloaded, I've noticed that now even mods that update within the same Factorio version are getting enabled by Factorio, even though the launcher says they're off. 

Example. I had just updated mods, and Helmod updated, but I double-checked that it was disabled before I launched, because it's not part of the pack I was launching. But once I'm in-game, it has been loaded.

![image](https://user-images.githubusercontent.com/127430/55295511-1490a100-53cb-11e9-81fa-2b2bc49bf624.png)

**Comment by Artentus** [comment]
Fixed in 1.10.2
