### ISSUE TITLE
mods installed mutiple times

### ISSUE THREAD

**Issue by szentigrad3** [Artentus/ModMyFactory#12]
so i just setup v1.2 and all is working except for load the game up and check screenshot here: https://s12.postimg.org/in3qe19wt/Untitled.png

**Comment by Artentus** [comment]
Have you at some point updated your mods through ModMyFactory? This is the only reason I can think of where multiple versions of a mod could end up in the mods folder.
For now I recommend to just clean up yourself. You can safely delete the duplicate mods in Windows Explorer, but delete the mod-list.json file as well so ModMyFactory can rebuild it.

**Comment by szentigrad3** [comment]
yer i did update the mods thru ModMyFactory, i see no duplicates in the mods folder of ModMyFactory
found them they were in %appdata%\Factorio\mods

**Comment by Artentus** [comment]
Maby they were synced from Steam? I am not sure which contents Steam will save in the cloud.
However, both folders should actually have the same contents because one of them should just be a junction to the other one.

**Comment by szentigrad3** [comment]
they ain't because i have steam sync off and when i did it only does the saves

**Comment by Artentus** [comment]
Yes, It can't be Steam.
However, I still do not understand how the contents of %AppData%\Factorio\mods and the ModMyFactory mods folder can be different for you. %AppData%\Factorio\mods should be a directory junction to the ModMyFactory mods folder (marked by a small link arrow in Windows Explorer).

**Comment by szentigrad3** [comment]
There is a small link arrow on it but the 2 folders differed.  When I opened %AppData%\Factorio\mods it showed that in the address bar if it's just linked when opened shouldn't it open to where the money factory is

**Comment by Artentus** [comment]
No it's correct that way.
A junction does not behave like a normal link, instead it "fakes" a path to exist.

**Comment by szentigrad3** [comment]
Yer I dunno it was only showing in %AppData%\Factorio\mods and not also the modmyfactory mods folder

**Comment by Artentus** [comment]
Please confirm that the folders are actually correctly linked (by creating a test file for example). You can view the destination of the junction by using the dir command in the console.

**Comment by szentigrad3** [comment]
I'm not at home atm, but does it matter what folder I do it from

**Comment by Artentus** [comment]
No problem, I am neither. ;)
And yes it does matter. Do it from %AppData%\Factorio. You should then see an entry that looks something like '<JUNCTION> mods [destination]'.

**Comment by szentigrad3** [comment]
i think i have fixed it... also anyway so that when i format i don't loose all the modpacks etc save them in the app folder instead of %appdata%\ModMyFactory

**Comment by Artentus** [comment]
It would be nice if you could tell me what the problem was so I can close this. :)

**Comment by szentigrad3** [comment]
for some reason it was detecting another mod folder i had somewhere else not in the app dir

**Comment by Artentus** [comment]
Ah, ok. Glad to hear this isn't actually a bug in ModMyFactory.
