### ISSUE TITLE
Add "Select/Deselect All" option in the mod list

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#14]
As in "Enable/Disable All" option.

**Comment by Artentus** [comment]
To deselect everything you can
- click on a free spot (group headers also work).
- Ctrl+Click on a single selected item (this will deselect it).

**Comment by alxcyl** [comment]
What I meant by "select/deselect" is to check/uncheck or enable/disable the mod. Sorry for the confusion

**Comment by Artentus** [comment]
Ah ok, that does sound like a useful feature.
Will see how I can implement that.

**Comment by Artentus** [comment]
Added in version 1.3.0.
