### ISSUE TITLE
Mods with dependencies can be selected even if the required mods do not exist

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#19]
For example, you can install Angel's Warehousing but you can't use it in-game because it requires Angel's Refining.

I don't know if that's within the scope of the project though.

**Comment by alxcyl** [comment]
Also applies for mods that require an older version of the game. (e.g. Bob's Research Saver requires Factorio version <= 0.14.8 with 0.14.16 installed)

**Comment by Artentus** [comment]
I could implement a check for dependencies but I doubt this is actually needed. Users should be able to create working modpacks themselves. Restricting this will most likely just complicate things.

**Comment by alxcyl** [comment]
Maybe add a warning? Like "Some of the mods you selected are missing dependencies. They will not be removed from the mod pack but will be disabled automatically in-game."

**Comment by Artentus** [comment]
Dependency handling has been implemented in version 1.7.0, although I decided against enforcing dependencies inside the manager.
