### ISSUE TITLE
Renaming should respond to the enter key

### ISSUE THREAD

**Issue by mheguy** [Artentus/ModMyFactory#2]
Currently when renaming a modpack hitting enter does not close the renaming prompt, neither does clicking away from it. Typical users would expect both of those actions to complete the renaming process.

**Comment by Artentus** [comment]
Enter will probably be in the next version, I noticed it, too.
I'll have to see if I can get clicking somewhere else to work.

**Comment by jodli** [comment]
Do you actually accept Pull Requests for this?

**Comment by Artentus** [comment]
I don't see why I wouldn't.
However, I might make some adjustments to merged code.
