### ISSUE TITLE
Program is completely unusable if not connected to the internet

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#20]
Crashes a few seconds after opening the program when trying to connect to GitHub for updates.

**Comment by jodli** [comment]
As a workaround for now there is a command line flag for the update check:
-u, --no-update: Don't search for update on startup.

**Comment by Artentus** [comment]
Handling of network errors will be part of 1.3.0

**Comment by Artentus** [comment]
Fixed as of version 1.3.0.
