### ISSUE TITLE
Get network error on updating mods

### ISSUE THREAD

**Issue by Data-Raider** [Artentus/ModMyFactory#22]
I have a mod that does not exist on the mod portal.  When trying to update mods, it gives a network connection error.   If I delete it and then update, everything works fine.   The app either needs to just skip it and continue or maybe a "don't update" property so it doesn't try to update

![modmyfactoryerror](https://cloud.githubusercontent.com/assets/23278341/20030481/1b813f96-a334-11e6-842c-009c1073a690.jpg)

**Comment by Artentus** [comment]
Fixed as of version 1.3.3.
