### ISSUE TITLE
Everytime you run ModMyFactory, an instance of cmd.exe runs in the background and does not stop even when ModMyFactory is closed

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#23]
Using Windows 7 Ultimate x64.

Reproduction:
1. Open Task Manager, switch to 'Processes' tab.
2. Run `ModMyFactory.exe`
3. Notice an instance of `cmd.exe` has appeared in the Task Manager.
4. Close and re-open `ModMyFactory.exe`.
5. Notice there's another instance of `cmd.exe`.
6. Close `ModMyFactory.exe`.
7. Try to delete ModMyFactory directory.
8. You can't delete ModMyFactory directory until `cmd.exe` process is ended.

**Comment by Artentus** [comment]
I am on it but the fix for this is not exactly straight forward.

**Comment by Artentus** [comment]
Fixed as of version 1.3.3.
