### ISSUE TITLE
Double-clicking mods should append it to the selected mod pack

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#3]
Drag and drop is too much of a hassle when making big mod packs with dozens of mods.

**Comment by Artentus** [comment]
You can select multiple mods (and modpacks) at once using Shift and Control, just like in Windows explorer. When you darg and drop, all selected mods/modpacks will be added.

I feel like double clicking will not be apparent to users, especially since multiple modpacks can be selected at once.

**Comment by alxcyl** [comment]
Well, fwiw, shift and ctrl modifiers are also not apparent. As for multiple mod packs, it should just add the mods to both packs.

**Comment by Artentus** [comment]
Shift and Control are default functions of list views every Windows user should be familiar with. Doubble clicking on the other hand normally opens an item (in some way or another), so adding as double click action will be counter intuitive.
