### ISSUE TITLE
Changing the Factorio install location should detect whether Factorio is in the specified location

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#4]
Under Settings -> Factorio location, I chose `E:\SteamLibrary\steamapps\common\Factorio` (where my Factorio installation is located). After clicking OK, it didn't appear on the Version Manager. When I clicked Add from Folder in the Version Manager, it says it will have to copy the folder to the specified folder (which is the same folder).

The Version Manager should automatically do this when I change the Factorio location.

**Comment by alxcyl** [comment]
It actually crashed when I clicked OK on the "this folder will be copied" dialog.

**Comment by Artentus** [comment]
The crash is not suprising. The Steam version of Factorio does not behave like the zipped versions. The location setting should therefore not be used to add the Steam version.
For now, there is no way to use the Steam version from within ModMyFactory. I will add support for it in a later patch, it's on my todo list.

**Comment by jodli** [comment]
It still wants to move the files from the folder to another folder because of how the app manages the different versions of the game.
Adding the Steam version of the game from folder (SteamLibrary/steamapps/common/Factorio) however worked great for me.

**Comment by Artentus** [comment]
But I guess Steam will then no longer detect the game, will it?
Anyway, I will add support for the steam version in a way that won't move any files so nothig will break.

**Comment by Artentus** [comment]
The Steam version of Factorio is supported as of version 1.2.0.
