### ISSUE TITLE
[Suggestion] Better(?) handling of modpacks

### ISSUE THREAD

**Issue by Alxandr** [Artentus/ModMyFactory#40]
I've not looked at the code for modmyfactory, but I noticed the fact that you're using junctions to effectively symlink the mods folder into the game, and I'm guessing that before launching the game you update the mods.json file with what mods are to be enabled/disabled (or some mechanism like that). However, I read somewhere that factorio has a mechanism for launching with a mods folder as the argument (something like `factorio.exe --mods <path to mods>`, albeit probably with a different switch) and this got me thinking that the mods/folders could probably be handled better, and as such I suggest that instead of having a single mods folder (which forces all of your mod packs to have compatible mods with eachother) instead create a folder per modpack where all the mods for *that* modpack lives. Then just launch the game pointing at the correct modpack. Do you think something like this would be doable?

**Comment by Artentus** [comment]
I deliberately decided against using the --mod-directory command line parameter for the following reasons:
- it's only supported since 0.13.10
- mods would either need to be stored twice or moved every time
- it would be incompatible with the ingame mod GUI

Also, not all mods need to be compatible with one another, only the currently active ones need to be.

**Comment by Alxandr** [comment]
Yes, I know that only currently active ones has to be, but what if I have one modpack requiring mod X version 1.0 and another requiring mod X using version 2.0? Also we live in the day and age of package managers like NPM and NuGet which just duplicates everything everywhere because developers have learned from years of DLL hell that it just makes life simpler. As for the ingame mod GUI I see no reason to use it if ModMyFactory is sufficiently good.

**Comment by Artentus** [comment]
> what if I have one modpack requiring mod X version 1.0 and another requiring mod X using version 2.0?

Have you actually encountered this? I have not.

Anyway, I decided to handle things this specific way and changing it would require a great amount of work. There probaby is not even a single best way.
