### ISSUE TITLE
"Import modpack" does not create an entry under the "modpacks" list

### ISSUE THREAD

**Issue by ahuff44** [Artentus/ModMyFactory#42]
When I import a modpack, I would expect the program to create a new modpack in the UI, but it doesn't.

I came across this when I tried to download a very similar modpack to one I previously downloaded; the newly added mods were selected on the left, but the already-existing mods were not selected, so I had to examine the FMP file by hand to figure out which mods I should select into a new modpack

**Comment by Artentus** [comment]
It should create a new one though.  
Did you have an existing modpack with the exact same name as the imported one? If so they will be merged (because there cannot be two modpacks with the same name).

**Comment by Artentus** [comment]
So I don't know if this is an actuall issue or not right now but the import will be reworked entirely in 1.6 anyway so I'm going to close this.
