### ISSUE TITLE
.15 Doesn't load mods

### ISSUE THREAD

**Issue by Nielwulf** [Artentus/ModMyFactory#46]
When I use ModMyFactory to launch factorio, it does not list mods in the mod list.

It can query the mods database, it can update the mods, it sees the new version of Factorio, but when I click start game, it doesn't load any of the mods that are selected.

**Comment by Artentus** [comment]
I feared 0.15 might change something about how mods are loaded.

I'll have to look into this. Depending on how much has changed this may or may not take a while to fix.

**Comment by Artentus** [comment]
So, I have just tested this and I am afraid I can not recreate this issue, mods appear correctly in Facorio and can be toggled.

Are you sure the mods you have installed target Factorio version 0.15? Only mods that target 0.15 will appear in the 0.15 mod list. Mods that target 0.14 will only appear in Factorio 0.14, and not that many mods have been updated yet.

**Comment by Nielwulf** [comment]
Thank you for looking into it. I thought I had at least one that was .15 compatible, but it looks like i am incorrect.

Perhaps i was caught up in the .15 excitement and looked too much into things. sorry to bother you about it.

**Comment by Artentus** [comment]
It's fine, no worries.
