### ISSUE TITLE
Version Manager Add from Folder does not work properly

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#5]
It copied the folder to the specified folder but it doesn't appear in the manager window.

**Comment by Artentus** [comment]
Did you try this with the Steam version? If so than see my other answer, the Steam version is not compatible with ModMyFactory. The 'Add from folder' option will only add versions from the factorio website (installer or zip).

**Comment by alxcyl** [comment]
I tried both Steam and the extracted ZIP from the website. Adding from ZIP works but if I use Add from folder and select the extracted ZIP, it doesn't work.

**Comment by Artentus** [comment]
Thats interesting. I will have a look at it.

**Comment by Artentus** [comment]
This bug is fixed as of version 1.0.6.
