### ISSUE TITLE
Apphang when clicking on "Shuttle Train Lite"

### ISSUE THREAD

**Issue by credomane** [Artentus/ModMyFactory#52]
Use MyModFactory to download mods and search for "Shuttle".

Click on any of the mods except "Shuttle Train Lite" they work just fine.
Now click on "Shuttle Train Lite". The app is now frozen.

Issue seems to be in parsing that extremely "long description" because the right pane shows the right title but the description of the previous mod.

Shuttle Train Lite @ mod portal: https://mods.factorio.com/mods/folk/folk-shuttle

**Comment by Artentus** [comment]
Must be an infinite loop in the parser, I'll look into it.

**Comment by Artentus** [comment]
Fixed for 1.5.9.
