### ISSUE TITLE
Version manager can't download non-steam version if same steam version is present.

### ISSUE THREAD

**Issue by credomane** [Artentus/ModMyFactory#55]
The version manager should ignore the current steam version of the Factorio when deciding what versions you can download.  
In this screenshot Steam(0.15.15) is preventing the install of the non-steam 0.15.15. If I manually download Factorio 0.15.15 from the website and install it through the zip method it works just fine. Showing both non-steam and steam Factorio 0.15.15 as installed.
![mmfns](https://cloud.githubusercontent.com/assets/1283031/26686454/8e61862a-46b2-11e7-81be-de8f499ae3f8.png)

On a side-note it would also be neat if experimental versions were sorted in order with the rest of the factorio versions instead of being tacked on to the end of the list.

**Comment by Artentus** [comment]
Implemented for 1.5.10.
