### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by GreenMan36** [Artentus/ModMyFactory#56]
# LOOK AT THE COMMENT DOWN BELOW
I downloaded everything but i have no idea how to use this, no _.exe_?
Do i need to build the app or anything?
If so, how do i do this?
**I need help!**

Thanks,

Jasper

**Comment by GreenMan36** [comment]
Never mind i found it, you should mayby add a link to the releases page becouse with google you will end up with the source code.
sorry :P

**Newest release download** [HERE](https://github.com/Artentus/ModMyFactory/releases/latest) be sure to **Download** the zip file and extract, _not the source code_.
^For the other nubs like me^

**Comment by Artentus** [comment]
I have added a link to the readme.
