### ISSUE TITLE
What do I modify to test out my own translation?

### ISSUE THREAD

**Issue by RuijieYu** [Artentus/ModMyFactory#59]
I just finished translating but I could only *commit* instead of testing it locally and then commit, which potentially takes a few more steps for me and also other contributors to perfect the translation. 

Thanks

**Comment by Artentus** [comment]
The only thing you have to do is to add an entry for your language in App.xaml right at the top. You can see the format required from the other translations.

After you have done this you should be able to debug and your language should appear in the menu.
