### ISSUE TITLE
Add option to start game/export links with multiple mod packs

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#6]
I had a mod pack I called "Essentials" which is basically some of the "must-have" mods like RSO, Autofill, LongReach, etc.

I would like to have this mod pack enabled along with other mod packs like Bob's or Angel's or Bob's+Angel's. However, exporting a link only allows to use one mod pack.

**Comment by Artentus** [comment]
This is intended behaviour. You can add modpacks to other modpacks, so if you want to start multiple modpacks, just add all of those to another modpack and start this one instead.
In your case, just add your 'Essentials' modpack to the 'Bob's + Angel's' modpack.

**Comment by alxcyl** [comment]
Alright.
