### ISSUE TITLE
Updating Mods When Factorio Run Causes MMF Crash

### ISSUE THREAD

**Issue by RuijieYu** [Artentus/ModMyFactory#61]
[crash-log.txt](https://github.com/Artentus/ModMyFactory/files/1210391/crash-log.txt)

This might be intended behavior, but I just want to point out that even with Factorio run without turning on any mods, when it tries to update mods (with deletion of old ones on), it crashes. 

Possible solutions to prevent crash: 

1. Somehow detect that factorio is not using any mods being updated, and bypass that error-throwing.

2. Keep the used mods for now despite the customized settings, and figure it out later. 

3. Ignore these mods being used and warn the user.

**Comment by Artentus** [comment]
Well I never designed ModMyFactory to work while Factorio is running.

I will look into displaying an actuall error message instead of it just crashing, but this is basically a non-issue.

**Comment by RuijieYu** [comment]
Yes I agree, I just thought it shouldn't just crash but display error message as you said.
