### ISSUE TITLE
Save "blueprint-storage.dat" per modpack

### ISSUE THREAD

**Issue by Uriei** [Artentus/ModMyFactory#64]
Everytime I switch modpacks or play vanilla, all the blueprints get the modded items deleted from it, and they don't get back when loading the modpack again, so I think that saving that file depending on the modpack loaded could alleviate a lot of headaches.

**Comment by Artentus** [comment]
I believe the Factorio devs will do something about that for 0.16.

**Comment by Uriei** [comment]
That would be great.

**Comment by Artentus** [comment]
In the latest Friday Facts this issue is confirmed to be fixed for 0.16:
https://www.factorio.com/blog/post/fff-211

So I don't think I will bother with adding this to ModMyFactory.
