### ISSUE TITLE
0.15.40 Doesn't load mods or modpack

### ISSUE THREAD

**Issue by necrogami** [Artentus/ModMyFactory#65]
I've got mods in the mods group on the left.

I've got a modpack on the right with a group of mods in it.

I've got mods selected with checkmarks from the modpack.

I press start and it doesn't load any mods. This also occurs if i try and use the shortcut link. Never loads any mods.

**Comment by Artentus** [comment]
It works fine for me.

Did you make sure the mods you have are compatible to the version of Factorio you are running?
