### ISSUE TITLE
Program wont start.

### ISSUE THREAD

**Issue by adorhun** [Artentus/ModMyFactory#68]
hi!
ive got the program, it stared like 3 times, then it stopped working. 
[ReportQueue.zip](https://github.com/Artentus/ModMyFactory/files/1616390/ReportQueue.zip)
> Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

>Problem signature:
P1: ModMyFactory.exe
P2: 1.5.11.0
P3: 59a3895d
P4: ModMyFactory
P5: 1.5.11.0
P6: 59a3895d
P7: 82
P8: 21
P9: System.NullReferenceException
P10: 

>Attached files:

>These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ModMyFactory.exe_fe20eeb5e83c1da82328d036f47b2a43f52dbcda_06a72171_1c3ad3bf

>Analysis symbol: 
Rechecking for solution: 0
Report Id: 980a094c-f76f-4a9b-89d6-2866e4752db3
Report Status: 96
Hashed bucket:

**Comment by Artentus** [comment]
Is there a crash log in %appdata%\ModMyFactory?

**Comment by adorhun** [comment]
no, only the folders and jsons.

**Comment by adorhun** [comment]
ok, so i deleted the settings json. now t started up.

**Comment by Artentus** [comment]
Great!

Something musst have messed it up. I'll close this for now, if it keeps happening regularly please tell me.
