### ISSUE TITLE
Allow exporting mod pack as JSON string for easier sharing

### ISSUE THREAD

**Issue by alxcyl** [Artentus/ModMyFactory#7]
It would be nice to have an option to export the selected mod pack as a JSON string/file or something that can be copy-pasted/uploaded to share mod packs across the internet.

The string/file will then be imported in the manager and any missing mods will be automatically downloaded using the Factorio Mods API.

**Comment by alxcyl** [comment]
Sorry, I misclicked the close issue button.

**Comment by Artentus** [comment]
Modpacks are saved as Json objects, as a matter of fact. You can find them in %AppData%\ModMyFactory\modpacks.json.

However, while I can add an export feature for modpacks, auto-downloading the missing mods is currently not possible. I will come back to this once mod downloading is implemented (which is on my todo list).

**Comment by Artentus** [comment]
Exporting and importing of modpacks is supported as of version 1.2.0.
