### ISSUE TITLE
Crash when updating mods

### ISSUE THREAD

**Issue by utoxin** [Artentus/ModMyFactory#71]
This started today, and may be related to the mod portal getting a major update / speedup. Updating mods crashes after downloading the first mod. Log attached.
[crash-log.txt](https://github.com/Artentus/ModMyFactory/files/1644991/crash-log.txt)

**Comment by Artentus** [comment]
Fixed for 1.5.12.

**Comment by sapid** [comment]
I'm still getting this crash in 1.5.12pre1.
