### ISSUE TITLE
Network Error with Working Internet

### ISSUE THREAD

**Issue by eleksploded** [Artentus/ModMyFactory#75]
The title says it all, I am getting a network error even though I have a working connection. I don't know that to do now. It phrases pages just fine, but fails when I try to download a mod.

**Comment by Artentus** [comment]
I am aware of this issue but I am currently not sure what's causing it. Some people seem to be affected while others are not so my best bet is it is dependant on settings.

**Comment by eleksploded** [comment]
What would you recommend I do? I really want to use this program.

**Comment by Artentus** [comment]
As workaround disable "Keep old mod versions when updating" and all sub-items in the settings, that seems to work for me. If any of them is enabled the error occurs.

**Comment by eleksploded** [comment]
That didn't work for me.

**Comment by Artentus** [comment]
Using the pre-release? 1.5.11 will definitely not work.

**Comment by eleksploded** [comment]
I am using 1.5.12-pre1 and it doesn't work

**Comment by Arathok** [comment]
Got the same Problem on 1.5.12 My PC is connected to the router via LAN (does the program only work with wireless?)

EDIT1: Access was granted through the Firewall via Windows "Allow Program to communicate" i did not set up specific rules, just manually allowed the program through. - Still getting the error
- my ISP is located in germany (in case somehow the error only affects non US-users)

**Comment by Artentus** [comment]
Your connection type and location does not matter, the problem is solely in the software. I will have a look at this in the near future when I find the time, for now the only thing I know is that it only occurs with certain settings as I had it working and not working at the same time with two different installations on the same computer.

**Comment by Arathok** [comment]
Hmm okay, any recommendations on the settings? I've changed nothing so far, after installing I used the "install from folder" option, to grab my steam installation and clicked on copy (since the "use steam installation" button always destroys the steam install.

**Comment by Artentus** [comment]
These are my settings that appear to work:
![image](https://user-images.githubusercontent.com/4554831/36274309-93d431d8-1287-11e8-8097-46ca9727c865.png)

**Comment by Uriei** [comment]
Oh, interesting, if I use my username instead of my email it seems to work!

**Comment by Arathok** [comment]
> Oh, interesting, if I use my username instead of my email it seems to work!

YES! That did it for me too! 
Changing Settings earlier didn't help though.

(As lazy student low level programmer i would just change the credential field to "Username" xD but i know that you will search for the true cause! Or maybe its a server thing... would be a nice workaround though, for the time being)

**Comment by Artentus** [comment]
Wait is that actually the problem? If that's so that would be rather good.

**Comment by Uriei** [comment]
Well, at least now we have a clue :P

**Comment by Arathok** [comment]
True, it seems the search for the external cause is over! Good luck Artentus on finding it in the code . (If it isnt it factoriomods fault)

If anyone else had this problem, i'd suggest answering to this thread / react to Urieis Comment, if that fixed it, so Artentus can see if there was only one cause to this.

**Comment by Uriei** [comment]
Maybe the portal API now handles non-alphanumeric characters differently than on the previous version. `¯\_(ツ)_/¯ `

**Comment by Arathok** [comment]
like the dots and @s ?

**Comment by Uriei** [comment]
Yeah, maybe, I don't know too much about coding though, but I've dealt with Regex and character coding enough to know that it could be a thing as simple as that.

**Comment by Artentus** [comment]
Ok I found the problem. I am currently using a GET request with the "username" parameter to download and update mods. Since the mod portal update the "username" parameter only takes the actual username though, if you want to use email there is now the "email" parameter.

Should be a fairly easy fix.
