### ISSUE TITLE
Issues with the new system, regarding mod versioning

### ISSUE THREAD

**Issue by GuiltyNeko** [Artentus/ModMyFactory#76]
Mods can have a factorio version _range_ now, which ModMyFactory doesn't seem to recognize. When trying to update a mod through ModMyFactory, even manually through the download menu. I'd appreciate a fix soon.

**Comment by Artentus** [comment]
I'll look into it

**Comment by Artentus** [comment]
Can you tell me a mod that has this particular problem? I did a bit of digging and so far it appears the "factorio_version" tag inside a mods info.json file still specifies a single Factorio version.

**Comment by credomane** [comment]
@GuiltyNeko Mods cannot have a mod range. The new mod portal only shows a range if a mod has uploaded files for multiple versions of factorio. It is a purely visual feature of the mod portal.

Your problem sounds like you are not running one of the 1.5.12pre versions which are the only versions that will work with the new mod portal. The current pre-release is [1.5.12pre2](https://github.com/Artentus/ModMyFactory/releases/tag/v.1.5.12pre2) as of this comment. Download that and try updating your mods again.
