### ISSUE TITLE
Mod description in the "Browse Online Mods" doesn't update when selecting mods.

### ISSUE THREAD

**Issue by credomane** [Artentus/ModMyFactory#77]
Steps to reproduce:

1. Launch ModMyFactory.
2. Hit F7 or File -> Add Mods -> Download
3. Click different mods in the list.

Notice that the mod name on the top right changes but the description below it does not change.

**Comment by Artentus** [comment]
I know about this. The information got removed from the API and I currently don't know how to get it back.

**Comment by credomane** [comment]
I was downloading the deps to SeaBlock last night after I made this issue and I noticed the the description partially works. I was constantly open/closing the "Browse Online Mods" window.

1. Launch ModMyFactory.
2. Hit F7 or File -> Add Mods -> Download
3. Click a mod, any mod in the list.
4. Close the "Browse Online Mods" window.
5. Hit F7 or File -> Add Mods -> Download
6. Notice the mod you last selected is still selected and the mod's description is on the right now.

The license, homepage, github links certainly seem to always be missing though.

When I browse https://mods.factorio.com/api/mods the description is there under the `summary` JSON field. The others are certainly no longer listed.

[edit]  
I poked around the code. I got it the description working again. I'll send a PR in a minute!

**Comment by Artentus** [comment]
Yea the summary still exists but it's not the same as the description. Previously ModMyFactory would display the long description that is shown on the mod portal (not ingame).

**Comment by credomane** [comment]
Oh that's right. I forgot. Well this will work for now as a substitute, right? I think the only other way to get it back is to literally scrap the mod portal webpage for the selected mod. :/

**Comment by Artentus** [comment]
It'll have to do for now. I do want the full description back though at some point. I fear the only way is to get it from the website, which would be a bummer since the API used to give it to me in a really easy to format way, which the HTML will not. I may ask the devs about this.
