### ISSUE TITLE
Browser Extension

### ISSUE THREAD

**Issue by GuiltyNeko** [Artentus/ModMyFactory#79]
As much as it would be unnecessary, it would be extremely convenient if there were a browser extension, so that you could go to the factorio mod portal & use the extension to tell ModMyFactory to download the mod of the page you're on. Again, unnecessary, but it could very well streamline mod downloading. Thanks for your time.

**Comment by Artentus** [comment]
I have no experience with development of browser add-ons. If someone wants to go ahead and take on this task, by all means please proceed, I'd be more than happy to do the work on the software side. But I alone will not be able to make this happen.
