### ISSUE TITLE
manager doesnt work at all

### ISSUE THREAD

**Issue by Smeagol001** [Artentus/ModMyFactory#81]
hey  somehow i cant seem to get the manager to work i added my steam install as version . it says its version 0.14.21 but its  not since its the lastest 0.16 installled and somehjow it doesnt start my modpacks i created

**Comment by Artentus** [comment]
Try to remove and re-add it. Make sure you select the correct path as described here: https://github.com/Artentus/ModMyFactory/wiki/Add-Factorio

**Comment by Smeagol001** [comment]
i cant even remove it .... i used the button for detecting steam version

**Comment by Artentus** [comment]
Well, you can "remove" it by deleting your settings file located in %appdata%\ModMyFactory.
Your mods and modpacks are not affected by this so don't worry.

**Comment by ghost** [comment]
Yea I just tried this software and it doesnt work for me either. I was able to figure out adding my steam version and it added my mod list but selecting active mods does nothing and I cant do anything with the modpacks side of the screen even when dragging and dropping. Was hoping for a mod manager I could make presets for mod configurations which I thought this did?

**Comment by Artentus** [comment]
You can add modpacks with "File->New Modpack" or with the "New Modpack" button in the toolbar (second from left). Once you have created a modpack you can drag and drop mods (and other modpacks) into it.

**Comment by GuiltyNeko** [comment]
Yeah, I had similar difficulties when first using it. The interface is great for those who know how to make it work, but for those new to the program, it's terribly confusing and non-intuitive. You should take a look to see if there's anything you can do to help that. And this isn't just me, either. I've had a few others use it, and they couldn't figure it out easily either. I had to guide them through it with discord. Please, make the interface more intuitive.

**Comment by Artentus** [comment]
If you have any suggestions you are more than welcome to tell me. I'm a programmer, not a UI designer, I don't really know what I'm doing in that regard besides making it work.

**Comment by GuiltyNeko** [comment]
Well firstly, one that would probably be pretty easy would be making it so that you can create a modpack from the right-click context menu when in the right-side pane. The existing modpack button is too small to be easily noticed by first-time users.

**Comment by Artentus** [comment]
I have made some improvements in the latest release. Please check it out and tell me what you think.

**Comment by GuiltyNeko** [comment]
It's excellent, I love it. Thank you much.

**Comment by Karrq** [comment]
I have successfully added the Steam version to the program, but when I try to play it doesn't load any mods. I've tried making a modpack, selecting it and activating it, as well as selecting and activating selected mods but it just won't work, since it always starts base factorio...

**Comment by GuiltyNeko** [comment]
Are you launching FROM the mod manager? Because when using it, you have to specifically select the factorio version from the drop-down menu in order for it to put the mods into the mods folder. If you don't do that, it won't work. And if you don't do that, it won't launch from the mod manager.

**Comment by Karrq** [comment]
Yes, I'm launching from the manager (hitting the green play game button thing) after I've selected Steam 0.16.51 (whatever the latest version is) from the dropdown menu to the right. I've even tried starting the manager as administrator. I'm on win10 64bit.
