### ISSUE TITLE
Crashes downloading mod

### ISSUE THREAD

**Issue by JoshCrook** [Artentus/ModMyFactory#85]
As far as I can tell, this happens with any mod.
`System.InvalidOperationException: The server sent an invalid mod file.`
[crash-log.txt](https://github.com/Artentus/ModMyFactory/files/2149883/crash-log.txt)

This is a fresh "install" of MMF on a new computer. Steam version of Factorio selected (0.16.51)
Windows 10 x64

**Comment by Artentus** [comment]
Happens if you are using an outdated version of MMF. The current stable version 1.5.11 is completely broken and non-functional since the mod portal update, you need to use the lastest pre-release as stated in the release info on the download page.
