### ISSUE TITLE
Feature Suggestion: Link to Mods page

### ISSUE THREAD

**Issue by sthorsten** [Artentus/ModMyFactory#87]
I really like this Mod Manager.
In the "Browse online mods" it would be nice to have a link to the mod page itself (e.g. https://mods.factorio.com/mod/angelsindustries) additionally to the License, Homepage and GitHub Links.

For some reason, my links for the License, Homepage and GitHub seems broken (its empty). I'm running ModMyFactory v1.5.12pre4

Good work with the program though 👍

**Comment by Artentus** [comment]
I know about the empty links. It's nothing I can really do about, the info just got removed from the API for whatever reason. I have asked the devs about it weeks ago but have not received an answer so I doubt it's ever comming back.

**Comment by Artentus** [comment]
So actually I just bumped my question on the forums and not only did I receive an answer but the devs actually added it back straight away. Really gotta love the Factorio devs, my thread must've just been burried before so they didn't see.

With such great news I will probably release the 1.5.12 stable tomorrow with the complete feature set from 1.5.11 available.

**Comment by sthorsten** [comment]
That's great news! 👍

**Comment by Artentus** [comment]
As of 1.5.12 stable this functionality is implemented.
