### ISSUE TITLE
Version 1.7.1 Wont Start Only Crashes

### ISSUE THREAD

**Issue by szereka** [Artentus/ModMyFactory#89]
Hello

When i have downloaded this program from github version 1.7.1 and try to start it. 
It gives me a pop up with FAIL to start errorlog in appdata folder.

System is Win 10 Enterprise x64 NOT Locked down from company can install anything with in reason.
Mem = 16Gb
Over 400GB free on Hdd

"Normal factorio install and zip files work purfect."

Error log is Attached to message 
[error-log.txt](https://github.com/Artentus/ModMyFactory/files/2420329/error-log.txt)
Changed Path for USER as it has my Realname in it
[settings.json.txt](https://github.com/Artentus/ModMyFactory/files/2420305/settings.json.txt)

Settings filename is MODIFIED to be able to get in here from *.json to *.json.txt

Can say that 1.6.0 Works for me 
Regards
Henrik H Aka Szereka

**Comment by szereka** [comment]
seems like the program cant create the default folder (mods,factorio,savegame,scenario) so some program bug if i create the pre folder it starts and Works

**Comment by Artentus** [comment]
Thanks for reporting. This was indeed a bug introduced in 1.7 and only affected the mod directory in particular. Fixed for 1.7.2.
