### ISSUE TITLE
Request for Future Enhansment/betterment for Program

### ISSUE THREAD

**Issue by szereka** [Artentus/ModMyFactory#90]
Hiya Devs/Author

My Request is as follow:
Would it be possible that you can move the settings file to Application folder so that app becomes Portable for A Possible to have it on a USB stick ??

The way i am thinking is your app checks if settings file is in start folder 
(for example X:/Myfactorios/settings.json plus your appfiles with the (Factorio,Mods,Savegame,Scenario) if not goto default AppData//// Mymodsfactorio. ) 

I know this might NOT be a priority but just a Request/Feature that might be ok or Be a real hassel to do.
becuse you might need to do a check for the driveletter for where the app start so the settings "X://Myfactorio//misc//misc" become right and then the folders path.

My Best Regards and 2 Pennys/Cents of thinking
Henrik H Aka Szereka

PS Many Thx for the Quick respone on Version 1.7.1 and update to 1.7.2 DS

**Comment by Artentus** [comment]
I have already planned to create a portable version at some point.
However that will only happen after the normal version is feature complete (which is not all that far off actually).

**Comment by szereka** [comment]
Nice to Hear.

Keep up the Good Work.
Regards
Henrik H

**Comment by Artentus** [comment]
Portable version is now available.

Note that if you are actually moving the portable version between different computers, features like stored credentials and a added Steam version may break as they depend on the computer.
