### ISSUE TITLE
Mod Versions

### ISSUE THREAD

**Issue by szereka** [Artentus/ModMyFactory#91]
Hiya

The Mini Problem I have is that i have: 

RSO-MOD 3.7.8 for a Public server and 
RSO-MOD 3.8.0 for a Private server 

But Factorio sees Both Versions even if i would like to use 3.7.8 in 1 Modpack and the 3.8.0 in a nother pack.
Could it be implemented that you can see/choose Mod version in the Pack that is in the folder ??
Instead for me to go to the mod folder and move 1 mod file or more to a nother folder ?

and So even if i Update All my Mods i can have the Modpack with a certant mod version and only update the version If/When server updates for that Modpack ? but others Dont 

My Best Regards
Henrik H Aka Szereka

**Comment by Artentus** [comment]
Not easily possible, no. ModMyFactory was designed to behave in the same way as Factorio itself does to ensure compatibility. Implementing a functionality like you describe would not only require significant changes to how MMF manages mods but would also break compatibility.

I heard that the ability to have multiple different versions of the same mod installed simultaneously is a planned feature for Factorio 0.17. Should this indeed be the case then ModMyFactory will also receive this ability, which at that point should also be rather straight forward to implement. However until 0.17 is actually released and we know for sure I won't make any assumptions.

**Comment by Artentus** [comment]
I've decided to retroactively add this feature to older Factorio versions in preparation for when 0.17 hits. It will be part of MMF version 1.10 whenever it's ready (hopefully in time for 0.17).
