### ISSUE TITLE
Crash When Logging In with Invalid Account

### ISSUE THREAD

**Issue by LutherNa** [Artentus/ModMyFactory#92]
I was getting an error log (which of course I accidentally deleted by reloading the program to see if it would work - "error.log.old", please) that began with the error text below every time I tried to download a mod with login information saved. I eventually figured out that the error was caused by my using a Factorio account that I had created that didn't have a game attached to it (or at least, the problem was fixed once I linked my Factorio and Steam accounts). Everything works now though, but a descriptive error popup would probably be helpful. 

`System.NullReferenceException: Object reference not set to an instance of an object.`
`at ModMyFactory.GlobalCredentials.LogIn(Window owner, String& loginToken)`

**Comment by Artentus** [comment]
I have had reports of this before, but I was never able to find the issue. You are the first person who is making the connection to not having the game license linked to the account, so that is some very helpful information, thank you.

**Comment by Artentus** [comment]
Is fixed for next release.
