### ISSUE TITLE
Version 1.8.6 portable Error lang/strings.**.xml

### ISSUE THREAD

**Issue by szereka** [Artentus/ModMyFactory#94]
Hello

Tryed to start 1.8.6 portable and got an error. log is in swedish so you might need to use google translate for the text but you might understad the text anyway 

The part that i can read out of the error log is that:
Kan inte hitta resursen lang/strings.zh.xaml.
= Cant find lang/strings.zh.xaml

Just and FYI 1.8.6 normal works but NOT portable

[error-log.txt](https://github.com/Artentus/ModMyFactory/files/2493627/error-log.txt)
[settings.json.txt](https://github.com/Artentus/ModMyFactory/files/2493630/settings.json.txt)
psst needed to change extension fromjson to json.txt to get it uploaded
.

**Comment by Artentus** [comment]
Thanks for telling me.
There was actually nothing wrong with the code, but for some reason a broken executable ended up in the archive. I have recompiled and reuploaded the portable archive.
