### ISSUE TITLE
crash when importing game folder

### ISSUE THREAD

**Issue by mikiww2** [Artentus/ModMyFactory#95]
Hi,

Factorio is located in C:\Program Files\Factorio\(folder of bin, data, etc)
ModMyFactory is located in C:\Users\Miki\Documents\ModMyFactory_1.8.6\(folder of ModMyFactory.exe, etc)

When I use "version manager" -> "add from folder" it start copying Factorio then crash.
from the [error-log.txt](https://github.com/Artentus/ModMyFactory/files/2497656/error-log.txt) it seems that there is a bug on the automatic build of the path, it will add Factorio sub-folder two times:
`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Miki\AppData\Roaming\ModMyFactory\Factorio\Factorio'.`

Btw, in C:\Users\Miki\AppData\Roaming\ModMyFactory there is the copied "Factorio" folder and an empty "mods" folder

**Comment by Artentus** [comment]
Fixed in the next release.
